import { Poppins } from 'next/font/google'

import { PlayerProvider } from '@/contexts/playerContext'

import '../scss/main.scss'

const inter = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PlayerProvider>
          {children}
        </PlayerProvider>
      </body>
    </html>
  )
}
